<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="edate" nsURI="http://www.example.org/edate" nsPrefix="edate">
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Birthday" eType="ecore:EDataType
	http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Apollo11">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FirstManOnMoonDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        defaultValueLiteral="1969-07-20T20:18:00.000+0000"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Member" eType="#//Person"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
