<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="eopposite"
    nsURI="http:///com.example.eopposite.ecore"
    nsPrefix="eopposite">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="TopLevel"
      eSuperTypes="#//NamedObject">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="leftees"
        upperBound="-1"
        eType="#//LeftHand"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="rightees"
        upperBound="-1"
        eType="#//RightHand"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="rightMultiples"
        upperBound="-1"
        eType="#//RightMultiple"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="NamedObject">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="LeftHand"
      eSuperTypes="#//NamedObject">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="rightee"
        eType="#//RightHand"
        eOpposite="#//RightHand/leftee"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="rightMultiple"
        eType="#//RightMultiple"
        eOpposite="#//RightMultiple/leftees"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="RightHand"
      eSuperTypes="#//NamedObject">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="leftee"
        eType="#//LeftHand"
        eOpposite="#//LeftHand/rightee"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="RightMultiple"
      eSuperTypes="#//NamedObject">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="leftees"
        upperBound="-1"
        eType="#//LeftHand"
        eOpposite="#//LeftHand/rightMultiple"/>
  </eClassifiers>
</ecore:EPackage>
