<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xpand3"
    nsURI="http://www.eclipse.org/m2t/xpand/xpand3" nsPrefix="xpand3">
  <eClassifiers xsi:type="ecore:EClass" name="SyntaxElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//SyntaxElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//ImportStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
        upperBound="-1" eType="#//declaration/AbstractDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportStatement" eSuperTypes="#//SyntaxElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedId" eType="#//Identifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifier" eSuperTypes="#//SyntaxElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaredParameter" eSuperTypes="#//SyntaxElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Identifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Identifier"
        containment="true"/>
  </eClassifiers>
  <eSubpackages name="expression" nsURI="http://www.eclipse.org/m2t/xpand/xpand3/expression"
      nsPrefix="expression">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractExpression" abstract="true"
        eSuperTypes="#//SyntaxElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanOperation" eSuperTypes="#//expression/BinaryOperation"/>
    <eClassifiers xsi:type="ecore:EClass" name="Cast" eSuperTypes="#//expression/AbstractExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Identifier"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//expression/AbstractExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ChainExpression" eSuperTypes="#//expression/AbstractExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="first" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//expression/AbstractExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstructorCallExpression" eSuperTypes="#//expression/AbstractExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Identifier"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureCall" eSuperTypes="#//expression/AbstractExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Identifier"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionExpression" eSuperTypes="#//expression/FeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="closure" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eleName" eType="#//Identifier"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationCall" eSuperTypes="#//expression/FeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
          eType="#//expression/AbstractExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeSelectExpression" eSuperTypes="#//expression/FeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeLiteral" eType="#//Identifier"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GlobalVarExpression" eSuperTypes="#//expression/AbstractExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="globalVarName" eType="#//Identifier"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IfExpression" eSuperTypes="#//expression/AbstractExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenPart" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elsePart" eType="#//expression/AbstractExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LetExpression" eSuperTypes="#//expression/AbstractExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="varExpression" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetExpression" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="varName" eType="#//Identifier"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ListLiteral" eSuperTypes="#//expression/AbstractExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//expression/AbstractExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//expression/AbstractExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="literalValue" eType="#//Identifier"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" eSuperTypes="#//expression/Literal"/>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteral" eSuperTypes="#//expression/Literal"/>
    <eClassifiers xsi:type="ecore:EClass" name="NullLiteral" eSuperTypes="#//expression/Literal"/>
    <eClassifiers xsi:type="ecore:EClass" name="RealLiteral" eSuperTypes="#//expression/Literal"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//expression/Literal"/>
    <eClassifiers xsi:type="ecore:EClass" name="SwitchExpression" eSuperTypes="#//expression/AbstractExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="switchExpr" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultExpr" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
          eType="#//expression/Case" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Case" eSuperTypes="#//SyntaxElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenPart" eType="#//expression/AbstractExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryOperation" eSuperTypes="#//expression/AbstractExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operator" eType="#//Identifier"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnaryOperation" eSuperTypes="#//expression/AbstractExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operator" eType="#//Identifier"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#//expression/AbstractExpression"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="statement" nsURI="http://www.eclipse.org/m2t/xpand/xpand3/statement"
      nsPrefix="statement">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractStatement" abstract="true"
        eSuperTypes="#//SyntaxElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExpandStatement" eSuperTypes="#//statement/AbstractStatement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="foreach" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//expression/AbstractExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="separator" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
          eType="#//Identifier" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExpressionStatement" eSuperTypes="#//statement/AbstractStatement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//expression/AbstractExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ErrorStatement" eSuperTypes="#//statement/AbstractStatement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="message" lowerBound="1"
          eType="#//expression/AbstractExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractStatementWithBody" abstract="true"
        eSuperTypes="#//statement/AbstractStatement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          upperBound="-1" eType="#//statement/AbstractStatement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FileStatement" eSuperTypes="#//statement/AbstractStatementWithBody">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fileNameExpression" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outletNameIdentifier"
          eType="#//Identifier" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="once" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ForEachStatement" eSuperTypes="#//statement/AbstractStatementWithBody">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="separator" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Identifier"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iteratorName" eType="#//Identifier"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#//statement/AbstractStatementWithBody">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseIf" eType="#//statement/IfStatement"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LetStatement" eSuperTypes="#//statement/AbstractStatementWithBody">
      <eStructuralFeatures xsi:type="ecore:EReference" name="varName" eType="#//Identifier"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="varValue" eType="#//expression/AbstractExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProtectStatement" eSuperTypes="#//statement/AbstractStatementWithBody">
      <eStructuralFeatures xsi:type="ecore:EReference" name="commentStart" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="commentEnd" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="disable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextStatement" eSuperTypes="#//statement/AbstractStatement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleteLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="declaration" nsURI="http://www.eclipse.org/m2t/xpand/xpand3/declaration"
      nsPrefix="declaration">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractDeclaration" abstract="true"
        eSuperTypes="#//SyntaxElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1"
          eType="#//File" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
          eType="#//DeclaredParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrivate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//expression/AbstractExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractNamedDeclaration" abstract="true"
        eSuperTypes="#//declaration/AbstractDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Identifier"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Definition" eSuperTypes="#//declaration/AbstractNamedDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1"
          eType="#//statement/AbstractStatement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Extension" eSuperTypes="#//declaration/AbstractNamedDeclaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cached" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//expression/AbstractExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//Identifier"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractAspect" abstract="true" eSuperTypes="#//declaration/AbstractDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pointcut" eType="#//Identifier"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="wildparams" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExtensionAspect" eSuperTypes="#//declaration/AbstractAspect">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expression/AbstractExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DefinitionAspect" eSuperTypes="#//declaration/AbstractAspect">
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1"
          eType="#//statement/AbstractStatement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Check" eSuperTypes="#//declaration/AbstractDeclaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorSeverity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="msg" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="#//expression/AbstractExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateExtension" eSuperTypes="#//declaration/Extension">
      <eStructuralFeatures xsi:type="ecore:EReference" name="toBeCreated" eType="#//DeclaredParameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JavaExtension" eSuperTypes="#//declaration/AbstractNamedDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="javaType" eType="#//Identifier"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="javaMethod" eType="#//Identifier"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="javaParamTypes" upperBound="-1"
          eType="#//Identifier" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
