<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore" nsPrefix="ecore" nsURI="http://www.eclipse.org/emf/2002/Ecore" xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <eClassifiers eSuperTypes="#//EStructuralFeature" name="EAttribute" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="#//EBoolean" name="iD" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures derived="true" eType="#//EDataType" lowerBound="1" name="eAttributeType" transient="true" volatile="true" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers eSuperTypes="#//EModelElement" name="EAnnotation" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="#//EString" name="source" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures containment="true" eType="#//EStringToStringMapEntry" name="details" xsi:type="ecore:EReference"/>
    <eStructuralFeatures eOpposite="#//EModelElement/eAnnotations" eType="#//EModelElement" name="eModelElement" transient="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eType="#//EObject" name="contents" xsi:type="ecore:EReference"/>
    <eStructuralFeatures eType="#//EObject" name="references" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers eSuperTypes="#//EClassifier" name="EClass" xsi:type="ecore:EClass">
    <eOperations eType="#//EBoolean" name="isSuperTypeOf">
      <eParameters eType="#//EClass" name="someClass"/>
    </eOperations>
    <eOperations eType="#//EInt" name="getFeatureCount"/>
    <eOperations eType="#//EStructuralFeature" name="getEStructuralFeature">
      <eParameters eType="#//EInt" name="featureID"/>
    </eOperations>
    <eOperations eType="#//EInt" name="getFeatureID">
      <eParameters eType="#//EStructuralFeature" name="feature"/>
    </eOperations>
    <eOperations eType="#//EStructuralFeature" name="getEStructuralFeature">
      <eParameters eType="#//EString" name="featureName"/>
    </eOperations>
    <eOperations eType="#//EInt" name="getOperationCount"/>
    <eOperations eType="#//EOperation" name="getEOperation">
      <eParameters eType="#//EInt" name="operationID"/>
    </eOperations>
    <eOperations eType="#//EInt" name="getOperationID">
      <eParameters eType="#//EOperation" name="operation"/>
    </eOperations>
    <eOperations eType="#//EOperation" name="getOverride">
      <eParameters eType="#//EOperation" name="operation"/>
    </eOperations>
    <eStructuralFeatures eType="#//EBoolean" name="abstract" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EBoolean" name="interface" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EClass" name="eSuperTypes" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eOpposite="#//EOperation/eContainingClass" eType="#//EOperation" name="eOperations" xsi:type="ecore:EReference"/>
    <eStructuralFeatures derived="true" eType="#//EAttribute" name="eAllAttributes" transient="true" volatile="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures derived="true" eType="#//EReference" name="eAllReferences" transient="true" volatile="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures derived="true" eType="#//EReference" name="eReferences" transient="true" volatile="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures derived="true" eType="#//EAttribute" name="eAttributes" transient="true" volatile="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures derived="true" eType="#//EReference" name="eAllContainments" transient="true" volatile="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures derived="true" eType="#//EOperation" name="eAllOperations" transient="true" volatile="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures derived="true" eType="#//EStructuralFeature" name="eAllStructuralFeatures" transient="true" volatile="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures derived="true" eType="#//EClass" name="eAllSuperTypes" transient="true" volatile="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures derived="true" eType="#//EAttribute" name="eIDAttribute" transient="true" volatile="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eOpposite="#//EStructuralFeature/eContainingClass" eType="#//EStructuralFeature" name="eStructuralFeatures" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eType="#//EGenericType" name="eGenericSuperTypes" xsi:type="ecore:EReference"/>
    <eStructuralFeatures derived="true" eType="#//EGenericType" name="eAllGenericSuperTypes" transient="true" volatile="true" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers abstract="true" eSuperTypes="#//ENamedElement" name="EClassifier" xsi:type="ecore:EClass">
    <eOperations eType="#//EBoolean" name="isInstance">
      <eParameters eType="#//EJavaObject" name="object"/>
    </eOperations>
    <eOperations eType="#//EInt" name="getClassifierID"/>
    <eStructuralFeatures eType="#//EString" name="instanceClassName" unsettable="true" volatile="true" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures derived="true" eType="#//EJavaClass" name="instanceClass" transient="true" volatile="true" xsi:type="ecore:EAttribute">
      <eGenericType eClassifier="#//EJavaClass">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures derived="true" eType="#//EJavaObject" name="defaultValue" transient="true" volatile="true" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EString" name="instanceTypeName" unsettable="true" volatile="true" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eOpposite="#//EPackage/eClassifiers" eType="#//EPackage" name="ePackage" transient="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eType="#//ETypeParameter" name="eTypeParameters" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers eSuperTypes="#//EClassifier" name="EDataType" xsi:type="ecore:EClass">
    <eStructuralFeatures defaultValueLiteral="true" eType="#//EBoolean" name="serializable" xsi:type="ecore:EAttribute"/>
  </eClassifiers>

  <eClassifiers eSuperTypes="#//EDataType" name="EEnum" xsi:type="ecore:EClass">
    <eOperations eType="#//EEnumLiteral" name="getEEnumLiteral">
      <eParameters eType="#//EString" name="name"/>
    </eOperations>
    <eOperations eType="#//EEnumLiteral" name="getEEnumLiteral">
      <eParameters eType="#//EInt" name="value"/>
    </eOperations>
    <eOperations eType="#//EEnumLiteral" name="getEEnumLiteralByLiteral">
      <eParameters eType="#//EString" name="literal"/>
    </eOperations>
    <eStructuralFeatures containment="true" eOpposite="#//EEnumLiteral/eEnum" eType="#//EEnumLiteral" name="eLiterals" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers eSuperTypes="#//ENamedElement" name="EEnumLiteral" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="#//EInt" name="value" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EEnumerator" name="instance" transient="true" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EString" name="literal" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eOpposite="#//EEnum/eLiterals" eType="#//EEnum" name="eEnum" transient="true" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers eSuperTypes="#//EModelElement" name="EFactory" xsi:type="ecore:EClass">
    <eOperations eType="#//EObject" name="create">
      <eParameters eType="#//EClass" name="eClass"/>
    </eOperations>
    <eOperations eType="#//EJavaObject" name="createFromString">
      <eParameters eType="#//EDataType" name="eDataType"/>
      <eParameters eType="#//EString" name="literalValue"/>
    </eOperations>
    <eOperations eType="#//EString" name="convertToString">
      <eParameters eType="#//EDataType" name="eDataType"/>
      <eParameters eType="#//EJavaObject" name="instanceValue"/>
    </eOperations>
    <eStructuralFeatures eOpposite="#//EPackage/eFactoryInstance" eType="#//EPackage" lowerBound="1" name="ePackage" transient="true" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers abstract="true" name="EModelElement" xsi:type="ecore:EClass">
    <eOperations eType="#//EAnnotation" name="getEAnnotation">
      <eParameters eType="#//EString" name="source"/>
    </eOperations>
    <eStructuralFeatures containment="true" eOpposite="#//EAnnotation/eModelElement" eType="#//EAnnotation" name="eAnnotations" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers abstract="true" eSuperTypes="#//EModelElement" name="ENamedElement" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="#//EString" name="name" xsi:type="ecore:EAttribute"/>
  </eClassifiers>

  <eClassifiers name="EObject" xsi:type="ecore:EClass">
    <eOperations eType="#//EClass" name="eClass"/>
    <eOperations eType="#//EBoolean" name="eIsProxy"/>
    <eOperations eType="#//EResource" name="eResource"/>
    <eOperations eType="#//EObject" name="eContainer"/>
    <eOperations eType="#//EStructuralFeature" name="eContainingFeature"/>
    <eOperations eType="#//EReference" name="eContainmentFeature"/>
    <eOperations eType="#//EEList" name="eContents">
      <eGenericType eClassifier="#//EEList">
        <eTypeArguments eClassifier="#//EObject"/>
      </eGenericType>
    </eOperations>
    <eOperations eType="#//ETreeIterator" name="eAllContents">
      <eGenericType eClassifier="#//ETreeIterator">
        <eTypeArguments eClassifier="#//EObject"/>
      </eGenericType>
    </eOperations>
    <eOperations eType="#//EEList" name="eCrossReferences">
      <eGenericType eClassifier="#//EEList">
        <eTypeArguments eClassifier="#//EObject"/>
      </eGenericType>
    </eOperations>
    <eOperations eType="#//EJavaObject" name="eGet">
      <eParameters eType="#//EStructuralFeature" name="feature"/>
    </eOperations>
    <eOperations eType="#//EJavaObject" name="eGet">
      <eParameters eType="#//EStructuralFeature" name="feature"/>
      <eParameters eType="#//EBoolean" name="resolve"/>
    </eOperations>
    <eOperations name="eSet">
      <eParameters eType="#//EStructuralFeature" name="feature"/>
      <eParameters eType="#//EJavaObject" name="newValue"/>
    </eOperations>
    <eOperations eType="#//EBoolean" name="eIsSet">
      <eParameters eType="#//EStructuralFeature" name="feature"/>
    </eOperations>
    <eOperations name="eUnset">
      <eParameters eType="#//EStructuralFeature" name="feature"/>
    </eOperations>
    <eOperations eType="#//EJavaObject" name="eInvoke">
      <eParameters eType="#//EOperation" name="operation"/>
      <eParameters eType="#//EEList" name="arguments">
        <eGenericType eClassifier="#//EEList">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>

  <eClassifiers eSuperTypes="#//ETypedElement" name="EOperation" xsi:type="ecore:EClass">
    <eOperations eType="#//EInt" name="getOperationID"/>
    <eOperations eType="#//EBoolean" name="isOverrideOf">
      <eParameters eType="#//EOperation" name="someOperation"/>
    </eOperations>
    <eStructuralFeatures eOpposite="#//EClass/eOperations" eType="#//EClass" name="eContainingClass" transient="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eType="#//ETypeParameter" name="eTypeParameters" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eOpposite="#//EParameter/eOperation" eType="#//EParameter" name="eParameters" xsi:type="ecore:EReference"/>
    <eStructuralFeatures eType="#//EClassifier" name="eExceptions" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eType="#//EGenericType" name="eGenericExceptions" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers eSuperTypes="#//ENamedElement" name="EPackage" xsi:type="ecore:EClass">
    <eOperations eType="#//EClassifier" name="getEClassifier">
      <eParameters eType="#//EString" name="name"/>
    </eOperations>
    <eStructuralFeatures eType="#//EString" name="nsURI" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EString" name="nsPrefix" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eOpposite="#//EFactory/ePackage" eType="#//EFactory" lowerBound="1" name="eFactoryInstance" transient="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eOpposite="#//EClassifier/ePackage" eType="#//EClassifier" name="eClassifiers" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eOpposite="#//EPackage/eSuperPackage" eType="#//EPackage" name="eSubpackages" xsi:type="ecore:EReference"/>
    <eStructuralFeatures eOpposite="#//EPackage/eSubpackages" eType="#//EPackage" name="eSuperPackage" transient="true" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers eSuperTypes="#//ETypedElement" name="EParameter" xsi:type="ecore:EClass">
    <eStructuralFeatures eOpposite="#//EOperation/eParameters" eType="#//EOperation" name="eOperation" transient="true" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers eSuperTypes="#//EStructuralFeature" name="EReference" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="#//EBoolean" name="containment" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures derived="true" eType="#//EBoolean" name="container" transient="true" volatile="true" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures defaultValueLiteral="true" eType="#//EBoolean" name="resolveProxies" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EReference" name="eOpposite" xsi:type="ecore:EReference"/>
    <eStructuralFeatures derived="true" eType="#//EClass" lowerBound="1" name="eReferenceType" transient="true" volatile="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures eType="#//EAttribute" name="eKeys" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers abstract="true" eSuperTypes="#//ETypedElement" name="EStructuralFeature" xsi:type="ecore:EClass">
    <eOperations eType="#//EInt" name="getFeatureID"/>
    <eOperations eType="#//EJavaClass" name="getContainerClass">
      <eGenericType eClassifier="#//EJavaClass">
        <eTypeArguments/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures defaultValueLiteral="true" eType="#//EBoolean" name="changeable" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EBoolean" name="volatile" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EBoolean" name="transient" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EString" name="defaultValueLiteral" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures derived="true" eType="#//EJavaObject" name="defaultValue" transient="true" volatile="true" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EBoolean" name="unsettable" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EBoolean" name="derived" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eOpposite="#//EClass/eStructuralFeatures" eType="#//EClass" name="eContainingClass" transient="true" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers abstract="true" eSuperTypes="#//ENamedElement" name="ETypedElement" xsi:type="ecore:EClass">
    <eStructuralFeatures defaultValueLiteral="true" eType="#//EBoolean" name="ordered" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures defaultValueLiteral="true" eType="#//EBoolean" name="unique" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EInt" name="lowerBound" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures defaultValueLiteral="1" eType="#//EInt" name="upperBound" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures derived="true" eType="#//EBoolean" name="many" transient="true" volatile="true" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures derived="true" eType="#//EBoolean" name="required" transient="true" volatile="true" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EClassifier" name="eType" volatile="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eType="#//EGenericType" name="eGenericType" volatile="true" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers name="EStringToStringMapEntry" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="#//EString" name="key" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//EString" name="value" xsi:type="ecore:EAttribute"/>
  </eClassifiers>

  <eClassifiers name="EGenericType" xsi:type="ecore:EClass">
    <eStructuralFeatures containment="true" eType="#//EGenericType" name="eUpperBound" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eType="#//EGenericType" name="eTypeArguments" xsi:type="ecore:EReference"/>
    <eStructuralFeatures derived="true" eType="#//EClassifier" lowerBound="1" name="eRawType" transient="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eType="#//EGenericType" name="eLowerBound" xsi:type="ecore:EReference"/>
    <eStructuralFeatures eType="#//ETypeParameter" name="eTypeParameter" xsi:type="ecore:EReference"/>
    <eStructuralFeatures eType="#//EClassifier" name="eClassifier" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers eSuperTypes="#//ENamedElement" name="ETypeParameter" xsi:type="ecore:EClass">
    <eStructuralFeatures containment="true" eType="#//EGenericType" name="eBounds" xsi:type="ecore:EReference"/>
  </eClassifiers>

  <eClassifiers name="EBigDecimal" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EBigInteger" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EBoolean" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EBooleanObject" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EByte" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EByteArray" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EByteObject" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EChar" xsi:type="ecore:EDataType"/>

  <eClassifiers name="ECharacterObject" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EDate" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EDiagnosticChain" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EDouble" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EDoubleObject" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EEList" xsi:type="ecore:EDataType">
    <eTypeParameters name="E"/>
  </eClassifiers>

  <eClassifiers name="EEnumerator" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EFeatureMap" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EFeatureMapEntry" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EFloat" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EFloatObject" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EInt" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EIntegerObject" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EJavaClass" xsi:type="ecore:EDataType">
    <eTypeParameters name="T"/>
  </eClassifiers>

  <eClassifiers name="EJavaObject" xsi:type="ecore:EDataType"/>

  <eClassifiers name="ELong" xsi:type="ecore:EDataType"/>

  <eClassifiers name="ELongObject" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EMap" xsi:type="ecore:EDataType">
    <eTypeParameters name="K"/>
    <eTypeParameters name="V"/>
  </eClassifiers>

  <eClassifiers name="EResource" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EResourceSet" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EShort" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EShortObject" xsi:type="ecore:EDataType"/>

  <eClassifiers name="EString" xsi:type="ecore:EDataType"/>

  <eClassifiers name="ETreeIterator" xsi:type="ecore:EDataType">
    <eTypeParameters name="E"/>
  </eClassifiers>

  <eClassifiers name="EInvocationTargetException" xsi:type="ecore:EDataType"/>

</ecore:EPackage>
