<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="company"
    nsURI="http:///com.example.company.ecore"
    nsPrefix="company">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Employee">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="phonebookEntry"
        eType="#//PhonebookEntry"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Department">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="employees"
        upperBound="-1"
        eType="#//Employee"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="manager"
        lowerBound="1"
        eType="#//Employee"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="number"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Company">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="departments"
        upperBound="-1"
        eType="#//Department"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="PhonebookEntry"/>
</ecore:EPackage>
