<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="ResourceTests"
    nsURI="http://www.example.org/ResourceTests"
    nsPrefix="ResourceTests">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Root">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="target"
        eType="#//ReferenceTarget"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="referrers"
        upperBound="-1"
        eType="#//Referrer"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ReferenceTarget"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Referrer">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="reference"
        eType="#//ReferenceTarget"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ETypes">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="string"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Hallo Welt!"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="emptyString"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="date"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        defaultValueLiteral="1976-05-27T12:13:14.123-0300"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="char"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"
        defaultValueLiteral="98"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="bool"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="double"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="3.14"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="int"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="10"/>
  </eClassifiers>
</ecore:EPackage>
