
#
# kdm.pri
# Copyright (C) Cátedra SAES-UMU 2010 <andres.senac@um.es>
# Copyright (C) INCHRON GmbH 2016 <soeren.henning@inchron.com>
#
# EMF4CPP is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EMF4CPP is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#


SOURCES += \
    kdm.cpp \
    kdm/KdmPackage.cpp \
    kdm/KdmFactory.cpp \
    kdm/KdmPackageImpl.cpp \
    kdm/KdmFactoryImpl.cpp \
    kdm/action.cpp \
    kdm/action/ActionPackage.cpp \
    kdm/action/ActionFactory.cpp \
    kdm/action/ActionPackageImpl.cpp \
    kdm/action/ActionFactoryImpl.cpp \
    kdm/action/ActionElement.cpp \
    kdm/action/ActionElementImpl.cpp \
    kdm/action/AbstractActionRelationship.cpp \
    kdm/action/AbstractActionRelationshipImpl.cpp \
    kdm/action/ControlFlow.cpp \
    kdm/action/ControlFlowImpl.cpp \
    kdm/action/Calls.cpp \
    kdm/action/CallsImpl.cpp \
    kdm/action/Creates.cpp \
    kdm/action/CreatesImpl.cpp \
    kdm/action/Reads.cpp \
    kdm/action/ReadsImpl.cpp \
    kdm/action/Writes.cpp \
    kdm/action/WritesImpl.cpp \
    kdm/action/CompliesTo.cpp \
    kdm/action/CompliesToImpl.cpp \
    kdm/action/Flow.cpp \
    kdm/action/FlowImpl.cpp \
    kdm/action/TrueFlow.cpp \
    kdm/action/TrueFlowImpl.cpp \
    kdm/action/FalseFlow.cpp \
    kdm/action/FalseFlowImpl.cpp \
    kdm/action/GuardedFlow.cpp \
    kdm/action/GuardedFlowImpl.cpp \
    kdm/action/UsesType.cpp \
    kdm/action/UsesTypeImpl.cpp \
    kdm/action/Addresses.cpp \
    kdm/action/AddressesImpl.cpp \
    kdm/action/ActionRelationship.cpp \
    kdm/action/ActionRelationshipImpl.cpp \
    kdm/action/Throws.cpp \
    kdm/action/ThrowsImpl.cpp \
    kdm/action/Dispatches.cpp \
    kdm/action/DispatchesImpl.cpp \
    kdm/action/EntryFlow.cpp \
    kdm/action/EntryFlowImpl.cpp \
    kdm/action/BlockUnit.cpp \
    kdm/action/BlockUnitImpl.cpp \
    kdm/action/ExceptionUnit.cpp \
    kdm/action/ExceptionUnitImpl.cpp \
    kdm/action/TryUnit.cpp \
    kdm/action/TryUnitImpl.cpp \
    kdm/action/FinallyUnit.cpp \
    kdm/action/FinallyUnitImpl.cpp \
    kdm/action/CatchUnit.cpp \
    kdm/action/CatchUnitImpl.cpp \
    kdm/action/ExitFlow.cpp \
    kdm/action/ExitFlowImpl.cpp \
    kdm/action/ExceptionFlow.cpp \
    kdm/action/ExceptionFlowImpl.cpp \
    kdm/build.cpp \
    kdm/build/BuildPackage.cpp \
    kdm/build/BuildFactory.cpp \
    kdm/build/BuildPackageImpl.cpp \
    kdm/build/BuildFactoryImpl.cpp \
    kdm/build/AbstractBuildElement.cpp \
    kdm/build/AbstractBuildElementImpl.cpp \
    kdm/build/BuildResource.cpp \
    kdm/build/BuildResourceImpl.cpp \
    kdm/build/BuildDescription.cpp \
    kdm/build/BuildDescriptionImpl.cpp \
    kdm/build/SymbolicLink.cpp \
    kdm/build/SymbolicLinkImpl.cpp \
    kdm/build/AbstractBuildRelationship.cpp \
    kdm/build/AbstractBuildRelationshipImpl.cpp \
    kdm/build/LinksTo.cpp \
    kdm/build/LinksToImpl.cpp \
    kdm/build/Consumes.cpp \
    kdm/build/ConsumesImpl.cpp \
    kdm/build/BuildModel.cpp \
    kdm/build/BuildModelImpl.cpp \
    kdm/build/BuildComponent.cpp \
    kdm/build/BuildComponentImpl.cpp \
    kdm/build/Supplier.cpp \
    kdm/build/SupplierImpl.cpp \
    kdm/build/Tool.cpp \
    kdm/build/ToolImpl.cpp \
    kdm/build/BuildElement.cpp \
    kdm/build/BuildElementImpl.cpp \
    kdm/build/BuildRelationship.cpp \
    kdm/build/BuildRelationshipImpl.cpp \
    kdm/build/SuppliedBy.cpp \
    kdm/build/SuppliedByImpl.cpp \
    kdm/build/Library.cpp \
    kdm/build/LibraryImpl.cpp \
    kdm/build/BuildStep.cpp \
    kdm/build/BuildStepImpl.cpp \
    kdm/build/Produces.cpp \
    kdm/build/ProducesImpl.cpp \
    kdm/build/SupportedBy.cpp \
    kdm/build/SupportedByImpl.cpp \
    kdm/build/BuildProduct.cpp \
    kdm/build/BuildProductImpl.cpp \
    kdm/build/DescribedBy.cpp \
    kdm/build/DescribedByImpl.cpp \
    kdm/code.cpp \
    kdm/code/CodePackage.cpp \
    kdm/code/CodeFactory.cpp \
    kdm/code/CodePackageImpl.cpp \
    kdm/code/CodeFactoryImpl.cpp \
    kdm/code/AbstractCodeElement.cpp \
    kdm/code/AbstractCodeElementImpl.cpp \
    kdm/code/CodeItem.cpp \
    kdm/code/CodeItemImpl.cpp \
    kdm/code/ComputationalObject.cpp \
    kdm/code/ComputationalObjectImpl.cpp \
    kdm/code/ControlElement.cpp \
    kdm/code/ControlElementImpl.cpp \
    kdm/code/MethodUnit.cpp \
    kdm/code/MethodUnitImpl.cpp \
    kdm/code/Module.cpp \
    kdm/code/ModuleImpl.cpp \
    kdm/code/CodeAssembly.cpp \
    kdm/code/CodeAssemblyImpl.cpp \
    kdm/code/CallableUnit.cpp \
    kdm/code/CallableUnitImpl.cpp \
    kdm/code/Datatype.cpp \
    kdm/code/DatatypeImpl.cpp \
    kdm/code/TemplateUnit.cpp \
    kdm/code/TemplateUnitImpl.cpp \
    kdm/code/TemplateParameter.cpp \
    kdm/code/TemplateParameterImpl.cpp \
    kdm/code/AbstractCodeRelationship.cpp \
    kdm/code/AbstractCodeRelationshipImpl.cpp \
    kdm/code/InstanceOf.cpp \
    kdm/code/InstanceOfImpl.cpp \
    kdm/code/CompilationUnit.cpp \
    kdm/code/CompilationUnitImpl.cpp \
    kdm/code/CodeModel.cpp \
    kdm/code/CodeModelImpl.cpp \
    kdm/code/DerivedType.cpp \
    kdm/code/DerivedTypeImpl.cpp \
    kdm/code/ArrayType.cpp \
    kdm/code/ArrayTypeImpl.cpp \
    kdm/code/PrimitiveType.cpp \
    kdm/code/PrimitiveTypeImpl.cpp \
    kdm/code/BooleanType.cpp \
    kdm/code/BooleanTypeImpl.cpp \
    kdm/code/CharType.cpp \
    kdm/code/CharTypeImpl.cpp \
    kdm/code/ClassUnit.cpp \
    kdm/code/ClassUnitImpl.cpp \
    kdm/code/CompositeType.cpp \
    kdm/code/CompositeTypeImpl.cpp \
    kdm/code/RecordType.cpp \
    kdm/code/RecordTypeImpl.cpp \
    kdm/code/EnumeratedType.cpp \
    kdm/code/EnumeratedTypeImpl.cpp \
    kdm/code/Extends.cpp \
    kdm/code/ExtendsImpl.cpp \
    kdm/code/ScaledType.cpp \
    kdm/code/ScaledTypeImpl.cpp \
    kdm/code/FloatType.cpp \
    kdm/code/FloatTypeImpl.cpp \
    kdm/code/HasType.cpp \
    kdm/code/HasTypeImpl.cpp \
    kdm/code/ImplementationOf.cpp \
    kdm/code/ImplementationOfImpl.cpp \
    kdm/code/Implements.cpp \
    kdm/code/ImplementsImpl.cpp \
    kdm/code/IntegerType.cpp \
    kdm/code/IntegerTypeImpl.cpp \
    kdm/code/InterfaceUnit.cpp \
    kdm/code/InterfaceUnitImpl.cpp \
    kdm/code/PointerType.cpp \
    kdm/code/PointerTypeImpl.cpp \
    kdm/code/DefinedType.cpp \
    kdm/code/DefinedTypeImpl.cpp \
    kdm/code/TypeUnit.cpp \
    kdm/code/TypeUnitImpl.cpp \
    kdm/code/RangeType.cpp \
    kdm/code/RangeTypeImpl.cpp \
    kdm/code/Signature.cpp \
    kdm/code/SignatureImpl.cpp \
    kdm/code/DataElement.cpp \
    kdm/code/DataElementImpl.cpp \
    kdm/code/StringType.cpp \
    kdm/code/StringTypeImpl.cpp \
    kdm/code/ChoiceType.cpp \
    kdm/code/ChoiceTypeImpl.cpp \
    kdm/code/NamespaceUnit.cpp \
    kdm/code/NamespaceUnitImpl.cpp \
    kdm/code/VisibleIn.cpp \
    kdm/code/VisibleInImpl.cpp \
    kdm/code/CommentUnit.cpp \
    kdm/code/CommentUnitImpl.cpp \
    kdm/code/SharedUnit.cpp \
    kdm/code/SharedUnitImpl.cpp \
    kdm/code/DecimalType.cpp \
    kdm/code/DecimalTypeImpl.cpp \
    kdm/code/DateType.cpp \
    kdm/code/DateTypeImpl.cpp \
    kdm/code/TimeType.cpp \
    kdm/code/TimeTypeImpl.cpp \
    kdm/code/VoidType.cpp \
    kdm/code/VoidTypeImpl.cpp \
    kdm/code/ValueElement.cpp \
    kdm/code/ValueElementImpl.cpp \
    kdm/code/Value.cpp \
    kdm/code/ValueImpl.cpp \
    kdm/code/ValueList.cpp \
    kdm/code/ValueListImpl.cpp \
    kdm/code/StorableUnit.cpp \
    kdm/code/StorableUnitImpl.cpp \
    kdm/code/MemberUnit.cpp \
    kdm/code/MemberUnitImpl.cpp \
    kdm/code/ParameterUnit.cpp \
    kdm/code/ParameterUnitImpl.cpp \
    kdm/code/ItemUnit.cpp \
    kdm/code/ItemUnitImpl.cpp \
    kdm/code/IndexUnit.cpp \
    kdm/code/IndexUnitImpl.cpp \
    kdm/code/SynonymType.cpp \
    kdm/code/SynonymTypeImpl.cpp \
    kdm/code/SequenceType.cpp \
    kdm/code/SequenceTypeImpl.cpp \
    kdm/code/BagType.cpp \
    kdm/code/BagTypeImpl.cpp \
    kdm/code/SetType.cpp \
    kdm/code/SetTypeImpl.cpp \
    kdm/code/CodeElement.cpp \
    kdm/code/CodeElementImpl.cpp \
    kdm/code/CodeRelationship.cpp \
    kdm/code/CodeRelationshipImpl.cpp \
    kdm/code/LanguageUnit.cpp \
    kdm/code/LanguageUnitImpl.cpp \
    kdm/code/OrdinalType.cpp \
    kdm/code/OrdinalTypeImpl.cpp \
    kdm/code/BitstringType.cpp \
    kdm/code/BitstringTypeImpl.cpp \
    kdm/code/OctetType.cpp \
    kdm/code/OctetTypeImpl.cpp \
    kdm/code/OctetstringType.cpp \
    kdm/code/OctetstringTypeImpl.cpp \
    kdm/code/BitType.cpp \
    kdm/code/BitTypeImpl.cpp \
    kdm/code/Imports.cpp \
    kdm/code/ImportsImpl.cpp \
    kdm/code/Package.cpp \
    kdm/code/PackageImpl.cpp \
    kdm/code/ParameterTo.cpp \
    kdm/code/ParameterToImpl.cpp \
    kdm/code/TemplateType.cpp \
    kdm/code/TemplateTypeImpl.cpp \
    kdm/code/PreprocessorDirective.cpp \
    kdm/code/PreprocessorDirectiveImpl.cpp \
    kdm/code/MacroDirective.cpp \
    kdm/code/MacroDirectiveImpl.cpp \
    kdm/code/MacroUnit.cpp \
    kdm/code/MacroUnitImpl.cpp \
    kdm/code/ConditionalDirective.cpp \
    kdm/code/ConditionalDirectiveImpl.cpp \
    kdm/code/IncludeDirective.cpp \
    kdm/code/IncludeDirectiveImpl.cpp \
    kdm/code/VariantTo.cpp \
    kdm/code/VariantToImpl.cpp \
    kdm/code/Expands.cpp \
    kdm/code/ExpandsImpl.cpp \
    kdm/code/Redefines.cpp \
    kdm/code/RedefinesImpl.cpp \
    kdm/code/GeneratedFrom.cpp \
    kdm/code/GeneratedFromImpl.cpp \
    kdm/code/Includes.cpp \
    kdm/code/IncludesImpl.cpp \
    kdm/code/HasValue.cpp \
    kdm/code/HasValueImpl.cpp \
    kdm/conceptual.cpp \
    kdm/conceptual/ConceptualPackage.cpp \
    kdm/conceptual/ConceptualFactory.cpp \
    kdm/conceptual/ConceptualPackageImpl.cpp \
    kdm/conceptual/ConceptualFactoryImpl.cpp \
    kdm/conceptual/ConceptualModel.cpp \
    kdm/conceptual/ConceptualModelImpl.cpp \
    kdm/conceptual/AbstractConceptualElement.cpp \
    kdm/conceptual/AbstractConceptualElementImpl.cpp \
    kdm/conceptual/TermUnit.cpp \
    kdm/conceptual/TermUnitImpl.cpp \
    kdm/conceptual/ConceptualContainer.cpp \
    kdm/conceptual/ConceptualContainerImpl.cpp \
    kdm/conceptual/FactUnit.cpp \
    kdm/conceptual/FactUnitImpl.cpp \
    kdm/conceptual/AbstractConceptualRelationship.cpp \
    kdm/conceptual/AbstractConceptualRelationshipImpl.cpp \
    kdm/conceptual/ConceptualRelationship.cpp \
    kdm/conceptual/ConceptualRelationshipImpl.cpp \
    kdm/conceptual/BehaviorUnit.cpp \
    kdm/conceptual/BehaviorUnitImpl.cpp \
    kdm/conceptual/RuleUnit.cpp \
    kdm/conceptual/RuleUnitImpl.cpp \
    kdm/conceptual/ScenarioUnit.cpp \
    kdm/conceptual/ScenarioUnitImpl.cpp \
    kdm/conceptual/ConceptualFlow.cpp \
    kdm/conceptual/ConceptualFlowImpl.cpp \
    kdm/conceptual/ConceptualElement.cpp \
    kdm/conceptual/ConceptualElementImpl.cpp \
    kdm/conceptual/ConceptualRole.cpp \
    kdm/conceptual/ConceptualRoleImpl.cpp \
    kdm/core.cpp \
    kdm/core/CorePackage.cpp \
    kdm/core/CoreFactory.cpp \
    kdm/core/CorePackageImpl.cpp \
    kdm/core/CoreFactoryImpl.cpp \
    kdm/core/Element.cpp \
    kdm/core/ElementImpl.cpp \
    kdm/core/ModelElement.cpp \
    kdm/core/ModelElementImpl.cpp \
    kdm/core/KDMEntity.cpp \
    kdm/core/KDMEntityImpl.cpp \
    kdm/core/KDMRelationship.cpp \
    kdm/core/KDMRelationshipImpl.cpp \
    kdm/core/AggregatedRelationship.cpp \
    kdm/core/AggregatedRelationshipImpl.cpp \
    kdm/data.cpp \
    kdm/data/DataPackage.cpp \
    kdm/data/DataFactory.cpp \
    kdm/data/DataPackageImpl.cpp \
    kdm/data/DataFactoryImpl.cpp \
    kdm/data/DataModel.cpp \
    kdm/data/DataModelImpl.cpp \
    kdm/data/AbstractDataElement.cpp \
    kdm/data/AbstractDataElementImpl.cpp \
    kdm/data/DataResource.cpp \
    kdm/data/DataResourceImpl.cpp \
    kdm/data/IndexElement.cpp \
    kdm/data/IndexElementImpl.cpp \
    kdm/data/UniqueKey.cpp \
    kdm/data/UniqueKeyImpl.cpp \
    kdm/data/Index.cpp \
    kdm/data/IndexImpl.cpp \
    kdm/data/AbstractDataRelationship.cpp \
    kdm/data/AbstractDataRelationshipImpl.cpp \
    kdm/data/KeyRelation.cpp \
    kdm/data/KeyRelationImpl.cpp \
    kdm/data/ReferenceKey.cpp \
    kdm/data/ReferenceKeyImpl.cpp \
    kdm/data/DataContainer.cpp \
    kdm/data/DataContainerImpl.cpp \
    kdm/data/Catalog.cpp \
    kdm/data/CatalogImpl.cpp \
    kdm/data/RelationalSchema.cpp \
    kdm/data/RelationalSchemaImpl.cpp \
    kdm/data/ColumnSet.cpp \
    kdm/data/ColumnSetImpl.cpp \
    kdm/data/RelationalTable.cpp \
    kdm/data/RelationalTableImpl.cpp \
    kdm/data/RelationalView.cpp \
    kdm/data/RelationalViewImpl.cpp \
    kdm/data/RecordFile.cpp \
    kdm/data/RecordFileImpl.cpp \
    kdm/data/DataEvent.cpp \
    kdm/data/DataEventImpl.cpp \
    kdm/data/XMLSchema.cpp \
    kdm/data/XMLSchemaImpl.cpp \
    kdm/data/AbstractContentElement.cpp \
    kdm/data/AbstractContentElementImpl.cpp \
    kdm/data/ComplexContentType.cpp \
    kdm/data/ComplexContentTypeImpl.cpp \
    kdm/data/AllContent.cpp \
    kdm/data/AllContentImpl.cpp \
    kdm/data/SeqContent.cpp \
    kdm/data/SeqContentImpl.cpp \
    kdm/data/ChoiceContent.cpp \
    kdm/data/ChoiceContentImpl.cpp \
    kdm/data/ContentItem.cpp \
    kdm/data/ContentItemImpl.cpp \
    kdm/data/GroupContent.cpp \
    kdm/data/GroupContentImpl.cpp \
    kdm/data/ContentRestriction.cpp \
    kdm/data/ContentRestrictionImpl.cpp \
    kdm/data/SimpleContentType.cpp \
    kdm/data/SimpleContentTypeImpl.cpp \
    kdm/data/ExtendedDataElement.cpp \
    kdm/data/ExtendedDataElementImpl.cpp \
    kdm/data/DataRelationship.cpp \
    kdm/data/DataRelationshipImpl.cpp \
    kdm/data/MixedContent.cpp \
    kdm/data/MixedContentImpl.cpp \
    kdm/data/ContentReference.cpp \
    kdm/data/ContentReferenceImpl.cpp \
    kdm/data/DataAction.cpp \
    kdm/data/DataActionImpl.cpp \
    kdm/data/ReadsColumnSet.cpp \
    kdm/data/ReadsColumnSetImpl.cpp \
    kdm/data/ContentAttribute.cpp \
    kdm/data/ContentAttributeImpl.cpp \
    kdm/data/TypedBy.cpp \
    kdm/data/TypedByImpl.cpp \
    kdm/data/ReferenceTo.cpp \
    kdm/data/ReferenceToImpl.cpp \
    kdm/data/RestrictionOf.cpp \
    kdm/data/RestrictionOfImpl.cpp \
    kdm/data/ExtensionTo.cpp \
    kdm/data/ExtensionToImpl.cpp \
    kdm/data/DatatypeOf.cpp \
    kdm/data/DatatypeOfImpl.cpp \
    kdm/data/HasContent.cpp \
    kdm/data/HasContentImpl.cpp \
    kdm/data/WritesColumnSet.cpp \
    kdm/data/WritesColumnSetImpl.cpp \
    kdm/data/ProducesDataEvent.cpp \
    kdm/data/ProducesDataEventImpl.cpp \
    kdm/data/DataSegment.cpp \
    kdm/data/DataSegmentImpl.cpp \
    kdm/data/ContentElement.cpp \
    kdm/data/ContentElementImpl.cpp \
    kdm/data/ManagesData.cpp \
    kdm/data/ManagesDataImpl.cpp \
    kdm/event.cpp \
    kdm/event/EventPackage.cpp \
    kdm/event/EventFactory.cpp \
    kdm/event/EventPackageImpl.cpp \
    kdm/event/EventFactoryImpl.cpp \
    kdm/event/EventModel.cpp \
    kdm/event/EventModelImpl.cpp \
    kdm/event/AbstractEventElement.cpp \
    kdm/event/AbstractEventElementImpl.cpp \
    kdm/event/Event.cpp \
    kdm/event/EventImpl.cpp \
    kdm/event/AbstractEventRelationship.cpp \
    kdm/event/AbstractEventRelationshipImpl.cpp \
    kdm/event/EventRelationship.cpp \
    kdm/event/EventRelationshipImpl.cpp \
    kdm/event/EventResource.cpp \
    kdm/event/EventResourceImpl.cpp \
    kdm/event/State.cpp \
    kdm/event/StateImpl.cpp \
    kdm/event/Transition.cpp \
    kdm/event/TransitionImpl.cpp \
    kdm/event/OnEntry.cpp \
    kdm/event/OnEntryImpl.cpp \
    kdm/event/OnExit.cpp \
    kdm/event/OnExitImpl.cpp \
    kdm/event/EventAction.cpp \
    kdm/event/EventActionImpl.cpp \
    kdm/event/ReadsState.cpp \
    kdm/event/ReadsStateImpl.cpp \
    kdm/event/ProducesEvent.cpp \
    kdm/event/ProducesEventImpl.cpp \
    kdm/event/ConsumesEvent.cpp \
    kdm/event/ConsumesEventImpl.cpp \
    kdm/event/NextState.cpp \
    kdm/event/NextStateImpl.cpp \
    kdm/event/InitialState.cpp \
    kdm/event/InitialStateImpl.cpp \
    kdm/event/EventElement.cpp \
    kdm/event/EventElementImpl.cpp \
    kdm/event/HasState.cpp \
    kdm/event/HasStateImpl.cpp \
    kdm/source.cpp \
    kdm/source/SourcePackage.cpp \
    kdm/source/SourceFactory.cpp \
    kdm/source/SourcePackageImpl.cpp \
    kdm/source/SourceFactoryImpl.cpp \
    kdm/source/SourceRef.cpp \
    kdm/source/SourceRefImpl.cpp \
    kdm/source/SourceRegion.cpp \
    kdm/source/SourceRegionImpl.cpp \
    kdm/source/InventoryModel.cpp \
    kdm/source/InventoryModelImpl.cpp \
    kdm/source/AbstractInventoryElement.cpp \
    kdm/source/AbstractInventoryElementImpl.cpp \
    kdm/source/InventoryItem.cpp \
    kdm/source/InventoryItemImpl.cpp \
    kdm/source/SourceFile.cpp \
    kdm/source/SourceFileImpl.cpp \
    kdm/source/Image.cpp \
    kdm/source/ImageImpl.cpp \
    kdm/source/ResourceDescription.cpp \
    kdm/source/ResourceDescriptionImpl.cpp \
    kdm/source/Configuration.cpp \
    kdm/source/ConfigurationImpl.cpp \
    kdm/source/InventoryContainer.cpp \
    kdm/source/InventoryContainerImpl.cpp \
    kdm/source/Directory.cpp \
    kdm/source/DirectoryImpl.cpp \
    kdm/source/Project.cpp \
    kdm/source/ProjectImpl.cpp \
    kdm/source/AbstractInventoryRelationship.cpp \
    kdm/source/AbstractInventoryRelationshipImpl.cpp \
    kdm/source/BinaryFile.cpp \
    kdm/source/BinaryFileImpl.cpp \
    kdm/source/ExecutableFile.cpp \
    kdm/source/ExecutableFileImpl.cpp \
    kdm/source/DependsOn.cpp \
    kdm/source/DependsOnImpl.cpp \
    kdm/source/InventoryElement.cpp \
    kdm/source/InventoryElementImpl.cpp \
    kdm/source/InventoryRelationship.cpp \
    kdm/source/InventoryRelationshipImpl.cpp \
    kdm/platform.cpp \
    kdm/platform/PlatformPackage.cpp \
    kdm/platform/PlatformFactory.cpp \
    kdm/platform/PlatformPackageImpl.cpp \
    kdm/platform/PlatformFactoryImpl.cpp \
    kdm/platform/AbstractPlatformElement.cpp \
    kdm/platform/AbstractPlatformElementImpl.cpp \
    kdm/platform/PlatformModel.cpp \
    kdm/platform/PlatformModelImpl.cpp \
    kdm/platform/AbstractPlatformRelationship.cpp \
    kdm/platform/AbstractPlatformRelationshipImpl.cpp \
    kdm/platform/Requires.cpp \
    kdm/platform/RequiresImpl.cpp \
    kdm/platform/ResourceType.cpp \
    kdm/platform/ResourceTypeImpl.cpp \
    kdm/platform/NamingResource.cpp \
    kdm/platform/NamingResourceImpl.cpp \
    kdm/platform/MarshalledResource.cpp \
    kdm/platform/MarshalledResourceImpl.cpp \
    kdm/platform/MessagingResource.cpp \
    kdm/platform/MessagingResourceImpl.cpp \
    kdm/platform/FileResource.cpp \
    kdm/platform/FileResourceImpl.cpp \
    kdm/platform/ExecutionResource.cpp \
    kdm/platform/ExecutionResourceImpl.cpp \
    kdm/platform/PlatformAction.cpp \
    kdm/platform/PlatformActionImpl.cpp \
    kdm/platform/ExternalActor.cpp \
    kdm/platform/ExternalActorImpl.cpp \
    kdm/platform/DataManager.cpp \
    kdm/platform/DataManagerImpl.cpp \
    kdm/platform/BindsTo.cpp \
    kdm/platform/BindsToImpl.cpp \
    kdm/platform/PlatformElement.cpp \
    kdm/platform/PlatformElementImpl.cpp \
    kdm/platform/PlatformRelationship.cpp \
    kdm/platform/PlatformRelationshipImpl.cpp \
    kdm/platform/PlatformEvent.cpp \
    kdm/platform/PlatformEventImpl.cpp \
    kdm/platform/LockResource.cpp \
    kdm/platform/LockResourceImpl.cpp \
    kdm/platform/DeployedSoftwareSystem.cpp \
    kdm/platform/DeployedSoftwareSystemImpl.cpp \
    kdm/platform/Machine.cpp \
    kdm/platform/MachineImpl.cpp \
    kdm/platform/DeployedComponent.cpp \
    kdm/platform/DeployedComponentImpl.cpp \
    kdm/platform/DeployedResource.cpp \
    kdm/platform/DeployedResourceImpl.cpp \
    kdm/platform/Loads.cpp \
    kdm/platform/LoadsImpl.cpp \
    kdm/platform/Spawns.cpp \
    kdm/platform/SpawnsImpl.cpp \
    kdm/platform/RuntimeResource.cpp \
    kdm/platform/RuntimeResourceImpl.cpp \
    kdm/platform/Thread.cpp \
    kdm/platform/ThreadImpl.cpp \
    kdm/platform/Process.cpp \
    kdm/platform/ProcessImpl.cpp \
    kdm/platform/ReadsResource.cpp \
    kdm/platform/ReadsResourceImpl.cpp \
    kdm/platform/WritesResource.cpp \
    kdm/platform/WritesResourceImpl.cpp \
    kdm/platform/ManagesResource.cpp \
    kdm/platform/ManagesResourceImpl.cpp \
    kdm/platform/DefinedBy.cpp \
    kdm/platform/DefinedByImpl.cpp \
    kdm/platform/StreamResource.cpp \
    kdm/platform/StreamResourceImpl.cpp \
    kdm/structure.cpp \
    kdm/structure/StructurePackage.cpp \
    kdm/structure/StructureFactory.cpp \
    kdm/structure/StructurePackageImpl.cpp \
    kdm/structure/StructureFactoryImpl.cpp \
    kdm/structure/AbstractStructureElement.cpp \
    kdm/structure/AbstractStructureElementImpl.cpp \
    kdm/structure/Subsystem.cpp \
    kdm/structure/SubsystemImpl.cpp \
    kdm/structure/Layer.cpp \
    kdm/structure/LayerImpl.cpp \
    kdm/structure/StructureModel.cpp \
    kdm/structure/StructureModelImpl.cpp \
    kdm/structure/Component.cpp \
    kdm/structure/ComponentImpl.cpp \
    kdm/structure/SoftwareSystem.cpp \
    kdm/structure/SoftwareSystemImpl.cpp \
    kdm/structure/AbstractStructureRelationship.cpp \
    kdm/structure/AbstractStructureRelationshipImpl.cpp \
    kdm/structure/StructureRelationship.cpp \
    kdm/structure/StructureRelationshipImpl.cpp \
    kdm/structure/ArchitectureView.cpp \
    kdm/structure/ArchitectureViewImpl.cpp \
    kdm/structure/StructureElement.cpp \
    kdm/structure/StructureElementImpl.cpp \
    kdm/kdm.cpp \
    kdm/kdm/KdmPackage.cpp \
    kdm/kdm/KdmFactory.cpp \
    kdm/kdm/KdmPackageImpl.cpp \
    kdm/kdm/KdmFactoryImpl.cpp \
    kdm/kdm/KDMFramework.cpp \
    kdm/kdm/KDMFrameworkImpl.cpp \
    kdm/kdm/KDMModel.cpp \
    kdm/kdm/KDMModelImpl.cpp \
    kdm/kdm/Audit.cpp \
    kdm/kdm/AuditImpl.cpp \
    kdm/kdm/Segment.cpp \
    kdm/kdm/SegmentImpl.cpp \
    kdm/kdm/Attribute.cpp \
    kdm/kdm/AttributeImpl.cpp \
    kdm/kdm/Annotation.cpp \
    kdm/kdm/AnnotationImpl.cpp \
    kdm/kdm/TagDefinition.cpp \
    kdm/kdm/TagDefinitionImpl.cpp \
    kdm/kdm/ExtendedValue.cpp \
    kdm/kdm/ExtendedValueImpl.cpp \
    kdm/kdm/Stereotype.cpp \
    kdm/kdm/StereotypeImpl.cpp \
    kdm/kdm/ExtensionFamily.cpp \
    kdm/kdm/ExtensionFamilyImpl.cpp \
    kdm/kdm/TaggedRef.cpp \
    kdm/kdm/TaggedRefImpl.cpp \
    kdm/kdm/TaggedValue.cpp \
    kdm/kdm/TaggedValueImpl.cpp \
    kdm/ui.cpp \
    kdm/ui/UiPackage.cpp \
    kdm/ui/UiFactory.cpp \
    kdm/ui/UiPackageImpl.cpp \
    kdm/ui/UiFactoryImpl.cpp \
    kdm/ui/AbstractUIElement.cpp \
    kdm/ui/AbstractUIElementImpl.cpp \
    kdm/ui/UIResource.cpp \
    kdm/ui/UIResourceImpl.cpp \
    kdm/ui/UIDisplay.cpp \
    kdm/ui/UIDisplayImpl.cpp \
    kdm/ui/Screen.cpp \
    kdm/ui/ScreenImpl.cpp \
    kdm/ui/Report.cpp \
    kdm/ui/ReportImpl.cpp \
    kdm/ui/UIModel.cpp \
    kdm/ui/UIModelImpl.cpp \
    kdm/ui/AbstractUIRelationship.cpp \
    kdm/ui/AbstractUIRelationshipImpl.cpp \
    kdm/ui/UILayout.cpp \
    kdm/ui/UILayoutImpl.cpp \
    kdm/ui/UIField.cpp \
    kdm/ui/UIFieldImpl.cpp \
    kdm/ui/DisplaysImage.cpp \
    kdm/ui/DisplaysImageImpl.cpp \
    kdm/ui/Displays.cpp \
    kdm/ui/DisplaysImpl.cpp \
    kdm/ui/UIFlow.cpp \
    kdm/ui/UIFlowImpl.cpp \
    kdm/ui/UIElement.cpp \
    kdm/ui/UIElementImpl.cpp \
    kdm/ui/UIRelationship.cpp \
    kdm/ui/UIRelationshipImpl.cpp \
    kdm/ui/UIAction.cpp \
    kdm/ui/UIActionImpl.cpp \
    kdm/ui/UIEvent.cpp \
    kdm/ui/UIEventImpl.cpp \
    kdm/ui/ReadsUI.cpp \
    kdm/ui/ReadsUIImpl.cpp \
    kdm/ui/WritesUI.cpp \
    kdm/ui/WritesUIImpl.cpp \
    kdm/ui/ManagesUI.cpp \
    kdm/ui/ManagesUIImpl.cpp \


HEADERS += \
    kdm.hpp \
    kdm_forward.hpp \
    kdm/KdmPackage.hpp \
    kdm/KdmFactory.hpp \
    kdm/action.hpp \
    kdm/action_forward.hpp \
    kdm/action/ActionPackage.hpp \
    kdm/action/ActionFactory.hpp \
    kdm/action/ActionElement.hpp \
    kdm/action/AbstractActionRelationship.hpp \
    kdm/action/ControlFlow.hpp \
    kdm/action/Calls.hpp \
    kdm/action/Creates.hpp \
    kdm/action/Reads.hpp \
    kdm/action/Writes.hpp \
    kdm/action/CompliesTo.hpp \
    kdm/action/Flow.hpp \
    kdm/action/TrueFlow.hpp \
    kdm/action/FalseFlow.hpp \
    kdm/action/GuardedFlow.hpp \
    kdm/action/UsesType.hpp \
    kdm/action/Addresses.hpp \
    kdm/action/ActionRelationship.hpp \
    kdm/action/Throws.hpp \
    kdm/action/Dispatches.hpp \
    kdm/action/EntryFlow.hpp \
    kdm/action/BlockUnit.hpp \
    kdm/action/ExceptionUnit.hpp \
    kdm/action/TryUnit.hpp \
    kdm/action/FinallyUnit.hpp \
    kdm/action/CatchUnit.hpp \
    kdm/action/ExitFlow.hpp \
    kdm/action/ExceptionFlow.hpp \
    kdm/build.hpp \
    kdm/build_forward.hpp \
    kdm/build/BuildPackage.hpp \
    kdm/build/BuildFactory.hpp \
    kdm/build/AbstractBuildElement.hpp \
    kdm/build/BuildResource.hpp \
    kdm/build/BuildDescription.hpp \
    kdm/build/SymbolicLink.hpp \
    kdm/build/AbstractBuildRelationship.hpp \
    kdm/build/LinksTo.hpp \
    kdm/build/Consumes.hpp \
    kdm/build/BuildModel.hpp \
    kdm/build/BuildComponent.hpp \
    kdm/build/Supplier.hpp \
    kdm/build/Tool.hpp \
    kdm/build/BuildElement.hpp \
    kdm/build/BuildRelationship.hpp \
    kdm/build/SuppliedBy.hpp \
    kdm/build/Library.hpp \
    kdm/build/BuildStep.hpp \
    kdm/build/Produces.hpp \
    kdm/build/SupportedBy.hpp \
    kdm/build/BuildProduct.hpp \
    kdm/build/DescribedBy.hpp \
    kdm/code.hpp \
    kdm/code_forward.hpp \
    kdm/code/CodePackage.hpp \
    kdm/code/CodeFactory.hpp \
    kdm/code/AbstractCodeElement.hpp \
    kdm/code/CodeItem.hpp \
    kdm/code/ComputationalObject.hpp \
    kdm/code/ControlElement.hpp \
    kdm/code/MethodUnit.hpp \
    kdm/code/Module.hpp \
    kdm/code/CodeAssembly.hpp \
    kdm/code/CallableUnit.hpp \
    kdm/code/Datatype.hpp \
    kdm/code/TemplateUnit.hpp \
    kdm/code/TemplateParameter.hpp \
    kdm/code/AbstractCodeRelationship.hpp \
    kdm/code/InstanceOf.hpp \
    kdm/code/CompilationUnit.hpp \
    kdm/code/CodeModel.hpp \
    kdm/code/DerivedType.hpp \
    kdm/code/ArrayType.hpp \
    kdm/code/PrimitiveType.hpp \
    kdm/code/BooleanType.hpp \
    kdm/code/CharType.hpp \
    kdm/code/ClassUnit.hpp \
    kdm/code/CompositeType.hpp \
    kdm/code/RecordType.hpp \
    kdm/code/EnumeratedType.hpp \
    kdm/code/Extends.hpp \
    kdm/code/ScaledType.hpp \
    kdm/code/FloatType.hpp \
    kdm/code/HasType.hpp \
    kdm/code/ImplementationOf.hpp \
    kdm/code/Implements.hpp \
    kdm/code/IntegerType.hpp \
    kdm/code/InterfaceUnit.hpp \
    kdm/code/PointerType.hpp \
    kdm/code/DefinedType.hpp \
    kdm/code/TypeUnit.hpp \
    kdm/code/RangeType.hpp \
    kdm/code/Signature.hpp \
    kdm/code/DataElement.hpp \
    kdm/code/StringType.hpp \
    kdm/code/ChoiceType.hpp \
    kdm/code/NamespaceUnit.hpp \
    kdm/code/VisibleIn.hpp \
    kdm/code/CommentUnit.hpp \
    kdm/code/SharedUnit.hpp \
    kdm/code/DecimalType.hpp \
    kdm/code/DateType.hpp \
    kdm/code/TimeType.hpp \
    kdm/code/VoidType.hpp \
    kdm/code/ValueElement.hpp \
    kdm/code/Value.hpp \
    kdm/code/ValueList.hpp \
    kdm/code/StorableUnit.hpp \
    kdm/code/MemberUnit.hpp \
    kdm/code/ParameterUnit.hpp \
    kdm/code/ItemUnit.hpp \
    kdm/code/IndexUnit.hpp \
    kdm/code/SynonymType.hpp \
    kdm/code/SequenceType.hpp \
    kdm/code/BagType.hpp \
    kdm/code/SetType.hpp \
    kdm/code/CodeElement.hpp \
    kdm/code/CodeRelationship.hpp \
    kdm/code/LanguageUnit.hpp \
    kdm/code/OrdinalType.hpp \
    kdm/code/BitstringType.hpp \
    kdm/code/OctetType.hpp \
    kdm/code/OctetstringType.hpp \
    kdm/code/BitType.hpp \
    kdm/code/Imports.hpp \
    kdm/code/Package.hpp \
    kdm/code/ParameterTo.hpp \
    kdm/code/TemplateType.hpp \
    kdm/code/PreprocessorDirective.hpp \
    kdm/code/MacroDirective.hpp \
    kdm/code/MacroUnit.hpp \
    kdm/code/ConditionalDirective.hpp \
    kdm/code/IncludeDirective.hpp \
    kdm/code/VariantTo.hpp \
    kdm/code/Expands.hpp \
    kdm/code/Redefines.hpp \
    kdm/code/GeneratedFrom.hpp \
    kdm/code/Includes.hpp \
    kdm/code/HasValue.hpp \
    kdm/conceptual.hpp \
    kdm/conceptual_forward.hpp \
    kdm/conceptual/ConceptualPackage.hpp \
    kdm/conceptual/ConceptualFactory.hpp \
    kdm/conceptual/ConceptualModel.hpp \
    kdm/conceptual/AbstractConceptualElement.hpp \
    kdm/conceptual/TermUnit.hpp \
    kdm/conceptual/ConceptualContainer.hpp \
    kdm/conceptual/FactUnit.hpp \
    kdm/conceptual/AbstractConceptualRelationship.hpp \
    kdm/conceptual/ConceptualRelationship.hpp \
    kdm/conceptual/BehaviorUnit.hpp \
    kdm/conceptual/RuleUnit.hpp \
    kdm/conceptual/ScenarioUnit.hpp \
    kdm/conceptual/ConceptualFlow.hpp \
    kdm/conceptual/ConceptualElement.hpp \
    kdm/conceptual/ConceptualRole.hpp \
    kdm/core.hpp \
    kdm/core_forward.hpp \
    kdm/core/CorePackage.hpp \
    kdm/core/CoreFactory.hpp \
    kdm/core/Element.hpp \
    kdm/core/ModelElement.hpp \
    kdm/core/KDMEntity.hpp \
    kdm/core/KDMRelationship.hpp \
    kdm/core/AggregatedRelationship.hpp \
    kdm/data.hpp \
    kdm/data_forward.hpp \
    kdm/data/DataPackage.hpp \
    kdm/data/DataFactory.hpp \
    kdm/data/DataModel.hpp \
    kdm/data/AbstractDataElement.hpp \
    kdm/data/DataResource.hpp \
    kdm/data/IndexElement.hpp \
    kdm/data/UniqueKey.hpp \
    kdm/data/Index.hpp \
    kdm/data/AbstractDataRelationship.hpp \
    kdm/data/KeyRelation.hpp \
    kdm/data/ReferenceKey.hpp \
    kdm/data/DataContainer.hpp \
    kdm/data/Catalog.hpp \
    kdm/data/RelationalSchema.hpp \
    kdm/data/ColumnSet.hpp \
    kdm/data/RelationalTable.hpp \
    kdm/data/RelationalView.hpp \
    kdm/data/RecordFile.hpp \
    kdm/data/DataEvent.hpp \
    kdm/data/XMLSchema.hpp \
    kdm/data/AbstractContentElement.hpp \
    kdm/data/ComplexContentType.hpp \
    kdm/data/AllContent.hpp \
    kdm/data/SeqContent.hpp \
    kdm/data/ChoiceContent.hpp \
    kdm/data/ContentItem.hpp \
    kdm/data/GroupContent.hpp \
    kdm/data/ContentRestriction.hpp \
    kdm/data/SimpleContentType.hpp \
    kdm/data/ExtendedDataElement.hpp \
    kdm/data/DataRelationship.hpp \
    kdm/data/MixedContent.hpp \
    kdm/data/ContentReference.hpp \
    kdm/data/DataAction.hpp \
    kdm/data/ReadsColumnSet.hpp \
    kdm/data/ContentAttribute.hpp \
    kdm/data/TypedBy.hpp \
    kdm/data/ReferenceTo.hpp \
    kdm/data/RestrictionOf.hpp \
    kdm/data/ExtensionTo.hpp \
    kdm/data/DatatypeOf.hpp \
    kdm/data/HasContent.hpp \
    kdm/data/WritesColumnSet.hpp \
    kdm/data/ProducesDataEvent.hpp \
    kdm/data/DataSegment.hpp \
    kdm/data/ContentElement.hpp \
    kdm/data/ManagesData.hpp \
    kdm/event.hpp \
    kdm/event_forward.hpp \
    kdm/event/EventPackage.hpp \
    kdm/event/EventFactory.hpp \
    kdm/event/EventModel.hpp \
    kdm/event/AbstractEventElement.hpp \
    kdm/event/Event.hpp \
    kdm/event/AbstractEventRelationship.hpp \
    kdm/event/EventRelationship.hpp \
    kdm/event/EventResource.hpp \
    kdm/event/State.hpp \
    kdm/event/Transition.hpp \
    kdm/event/OnEntry.hpp \
    kdm/event/OnExit.hpp \
    kdm/event/EventAction.hpp \
    kdm/event/ReadsState.hpp \
    kdm/event/ProducesEvent.hpp \
    kdm/event/ConsumesEvent.hpp \
    kdm/event/NextState.hpp \
    kdm/event/InitialState.hpp \
    kdm/event/EventElement.hpp \
    kdm/event/HasState.hpp \
    kdm/source.hpp \
    kdm/source_forward.hpp \
    kdm/source/SourcePackage.hpp \
    kdm/source/SourceFactory.hpp \
    kdm/source/SourceRef.hpp \
    kdm/source/SourceRegion.hpp \
    kdm/source/InventoryModel.hpp \
    kdm/source/AbstractInventoryElement.hpp \
    kdm/source/InventoryItem.hpp \
    kdm/source/SourceFile.hpp \
    kdm/source/Image.hpp \
    kdm/source/ResourceDescription.hpp \
    kdm/source/Configuration.hpp \
    kdm/source/InventoryContainer.hpp \
    kdm/source/Directory.hpp \
    kdm/source/Project.hpp \
    kdm/source/AbstractInventoryRelationship.hpp \
    kdm/source/BinaryFile.hpp \
    kdm/source/ExecutableFile.hpp \
    kdm/source/DependsOn.hpp \
    kdm/source/InventoryElement.hpp \
    kdm/source/InventoryRelationship.hpp \
    kdm/platform.hpp \
    kdm/platform_forward.hpp \
    kdm/platform/PlatformPackage.hpp \
    kdm/platform/PlatformFactory.hpp \
    kdm/platform/AbstractPlatformElement.hpp \
    kdm/platform/PlatformModel.hpp \
    kdm/platform/AbstractPlatformRelationship.hpp \
    kdm/platform/Requires.hpp \
    kdm/platform/ResourceType.hpp \
    kdm/platform/NamingResource.hpp \
    kdm/platform/MarshalledResource.hpp \
    kdm/platform/MessagingResource.hpp \
    kdm/platform/FileResource.hpp \
    kdm/platform/ExecutionResource.hpp \
    kdm/platform/PlatformAction.hpp \
    kdm/platform/ExternalActor.hpp \
    kdm/platform/DataManager.hpp \
    kdm/platform/BindsTo.hpp \
    kdm/platform/PlatformElement.hpp \
    kdm/platform/PlatformRelationship.hpp \
    kdm/platform/PlatformEvent.hpp \
    kdm/platform/LockResource.hpp \
    kdm/platform/DeployedSoftwareSystem.hpp \
    kdm/platform/Machine.hpp \
    kdm/platform/DeployedComponent.hpp \
    kdm/platform/DeployedResource.hpp \
    kdm/platform/Loads.hpp \
    kdm/platform/Spawns.hpp \
    kdm/platform/RuntimeResource.hpp \
    kdm/platform/Thread.hpp \
    kdm/platform/Process.hpp \
    kdm/platform/ReadsResource.hpp \
    kdm/platform/WritesResource.hpp \
    kdm/platform/ManagesResource.hpp \
    kdm/platform/DefinedBy.hpp \
    kdm/platform/StreamResource.hpp \
    kdm/structure.hpp \
    kdm/structure_forward.hpp \
    kdm/structure/StructurePackage.hpp \
    kdm/structure/StructureFactory.hpp \
    kdm/structure/AbstractStructureElement.hpp \
    kdm/structure/Subsystem.hpp \
    kdm/structure/Layer.hpp \
    kdm/structure/StructureModel.hpp \
    kdm/structure/Component.hpp \
    kdm/structure/SoftwareSystem.hpp \
    kdm/structure/AbstractStructureRelationship.hpp \
    kdm/structure/StructureRelationship.hpp \
    kdm/structure/ArchitectureView.hpp \
    kdm/structure/StructureElement.hpp \
    kdm/kdm.hpp \
    kdm/kdm_forward.hpp \
    kdm/kdm/KdmPackage.hpp \
    kdm/kdm/KdmFactory.hpp \
    kdm/kdm/KDMFramework.hpp \
    kdm/kdm/KDMModel.hpp \
    kdm/kdm/Audit.hpp \
    kdm/kdm/Segment.hpp \
    kdm/kdm/Attribute.hpp \
    kdm/kdm/Annotation.hpp \
    kdm/kdm/TagDefinition.hpp \
    kdm/kdm/ExtendedValue.hpp \
    kdm/kdm/Stereotype.hpp \
    kdm/kdm/ExtensionFamily.hpp \
    kdm/kdm/TaggedRef.hpp \
    kdm/kdm/TaggedValue.hpp \
    kdm/ui.hpp \
    kdm/ui_forward.hpp \
    kdm/ui/UiPackage.hpp \
    kdm/ui/UiFactory.hpp \
    kdm/ui/AbstractUIElement.hpp \
    kdm/ui/UIResource.hpp \
    kdm/ui/UIDisplay.hpp \
    kdm/ui/Screen.hpp \
    kdm/ui/Report.hpp \
    kdm/ui/UIModel.hpp \
    kdm/ui/AbstractUIRelationship.hpp \
    kdm/ui/UILayout.hpp \
    kdm/ui/UIField.hpp \
    kdm/ui/DisplaysImage.hpp \
    kdm/ui/Displays.hpp \
    kdm/ui/UIFlow.hpp \
    kdm/ui/UIElement.hpp \
    kdm/ui/UIRelationship.hpp \
    kdm/ui/UIAction.hpp \
    kdm/ui/UIEvent.hpp \
    kdm/ui/ReadsUI.hpp \
    kdm/ui/WritesUI.hpp \
    kdm/ui/ManagesUI.hpp \

